const DEMO={settings:{days:5,periods:7},teachers:[{id:'t1',name:'Anita Sharma',code:'AS',max:5,unavailable:'Mon-1'},{id:'t2',name:'Ravi Kumar',code:'RK',max:5,unavailable:'Fri-7'},{id:'t3',name:'Neha Iyer',code:'NI',max:4,unavailable:'Wed-1,Wed-2'},{id:'t4',name:'Joseph D’Souza',code:'JD',max:5,unavailable:''},{id:'t5',name:'Priya Nair',code:'PN',max:4,unavailable:'Tue-6,Tue-7'},{id:'t6',name:'Arun Das',code:'AD',max:5,unavailable:''}],classes:[{id:'c1',grade:'6',section:'A',room:'R-101'},{id:'c2',grade:'6',section:'B',room:'R-102'},{id:'c3',grade:'7',section:'A',room:'R-201'},{id:'c4',grade:'7',section:'B',room:'R-202'}],rooms:['R-101','R-102','R-201','R-202','Science Lab','Computer Lab','Activity Hall'],lessons:[
{id:'l1',classId:'c1',subject:'Mathematics',teacherId:'t1',count:5,room:''},{id:'l2',classId:'c1',subject:'English',teacherId:'t2',count:5,room:''},{id:'l3',classId:'c1',subject:'Science',teacherId:'t3',count:4,room:'Science Lab'},{id:'l4',classId:'c1',subject:'Social Studies',teacherId:'t4',count:3,room:''},{id:'l5',classId:'c1',subject:'Hindi',teacherId:'t5',count:3,room:''},{id:'l6',classId:'c1',subject:'Computer Science',teacherId:'t6',count:2,room:'Computer Lab'},
{id:'l7',classId:'c2',subject:'Mathematics',teacherId:'t1',count:5,room:''},{id:'l8',classId:'c2',subject:'English',teacherId:'t2',count:5,room:''},{id:'l9',classId:'c2',subject:'Science',teacherId:'t3',count:4,room:'Science Lab'},{id:'l10',classId:'c2',subject:'Social Studies',teacherId:'t4',count:3,room:''},{id:'l11',classId:'c2',subject:'Hindi',teacherId:'t5',count:3,room:''},{id:'l12',classId:'c2',subject:'Art',teacherId:'t6',count:2,room:'Activity Hall'},
{id:'l13',classId:'c3',subject:'Mathematics',teacherId:'t1',count:5,room:''},{id:'l14',classId:'c3',subject:'English',teacherId:'t2',count:4,room:''},{id:'l15',classId:'c3',subject:'Science',teacherId:'t3',count:5,room:'Science Lab'},{id:'l16',classId:'c3',subject:'Social Studies',teacherId:'t4',count:4,room:''},{id:'l17',classId:'c3',subject:'Hindi',teacherId:'t5',count:3,room:''},
{id:'l18',classId:'c4',subject:'Mathematics',teacherId:'t1',count:5,room:''},{id:'l19',classId:'c4',subject:'English',teacherId:'t2',count:4,room:''},{id:'l20',classId:'c4',subject:'Science',teacherId:'t3',count:5,room:'Science Lab'},{id:'l21',classId:'c4',subject:'Social Studies',teacherId:'t4',count:4,room:''},{id:'l22',classId:'c4',subject:'Hindi',teacherId:'t5',count:3,room:''},{id:'l23',classId:'c4',subject:'Computer Science',teacherId:'t6',count:2,room:'Computer Lab'}]};
let state=load(),schedule=[],unplaced=[];const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
function load(){try{return JSON.parse(localStorage.getItem('shala-state'))||structuredClone(DEMO)}catch{return structuredClone(DEMO)}}
function save(){localStorage.setItem('shala-state',JSON.stringify(state));toast('Changes saved locally')}
const className=id=>{const c=state.classes.find(x=>x.id===id);return c?`Grade ${c.grade}${c.section}`:'Unknown'};
const teacherName=id=>state.teachers.find(x=>x.id===id)?.name||'Unknown';
function showView(name){$$('.view').forEach(v=>v.classList.toggle('active',v.id===`${name}-view`));$$('.nav-item[data-view]').forEach(n=>n.classList.toggle('active',n.dataset.view===name));const titles={dashboard:['Academic year 2026–27','Good morning, Meera'],setup:['Timetable foundation','School setup'],requirements:['Weekly teaching plan','Lesson requirements'],timetable:['Generated plan','Weekly timetable']};$('#page-eyebrow').textContent=titles[name][0];$('#page-title').textContent=titles[name][1];$('.sidebar').classList.remove('open');if(name==='timetable')renderScheduleControls()}
function render(){renderDashboard();renderSetup();renderLessons();$('#working-days').value=state.settings.days;$('#periods-day').value=state.settings.periods}
function renderDashboard(){const total=state.lessons.reduce((n,l)=>n+Number(l.count),0);const data=[['♙',state.teachers.length,'Teachers'],['▣',state.classes.length,'Classes'],['▦',total,'Lessons / week'],['⌂',state.rooms.length,'Rooms']];$('#metrics').innerHTML=data.map(x=>`<div class="metric"><div class="metric-top"><span class="metric-icon">${x[0]}</span></div><strong>${x[1]}</strong><small>${x[2]}</small></div>`).join('');const checks=[['Teachers added',!!state.teachers.length],['Classes created',!!state.classes.length],['Rooms available',!!state.rooms.length],['Lessons assigned',!!state.lessons.length]];const done=checks.filter(x=>x[1]).length,pct=Math.round(done/checks.length*100);$('#ready-percent').textContent=pct+'%';$('#ready-bar').style.width=pct+'%';$('#checklist').innerHTML=checks.map(x=>`<div class="check-item"><i>${x[1]?'✓':'·'}</i>${x[0]}</div>`).join('');const loads=state.teachers.map(t=>({code:t.code,n:state.lessons.filter(l=>l.teacherId===t.id).reduce((a,l)=>a+Number(l.count),0)})),max=Math.max(...loads.map(x=>x.n),1);$('#load-chart').innerHTML=loads.map(x=>`<div class="bar-col"><i style="height:${x.n/max*100}%" title="${x.n} lessons"></i><b>${x.code}</b></div>`).join('')}
function renderSetup(){$('#teacher-count').textContent=`${state.teachers.length} teaching staff`;$('#class-count').textContent=`${state.classes.length} class groups`;$('#room-count').textContent=`${state.rooms.length} spaces`;$('#teachers-body').innerHTML=state.teachers.map(t=>`<tr><td><strong>${esc(t.name)}</strong></td><td>${esc(t.code)}</td><td>${t.max} periods</td><td class="muted">${esc(t.unavailable||'None')}</td><td><button class="row-action" data-delete="teacher" data-id="${t.id}">×</button></td></tr>`).join('');$('#classes-body').innerHTML=state.classes.map(c=>`<tr><td><strong>Grade ${esc(c.grade)}</strong></td><td>${esc(c.section)}</td><td>${esc(c.room)}</td><td><button class="row-action" data-delete="class" data-id="${c.id}">×</button></td></tr>`).join('');$('#rooms-list').innerHTML=state.rooms.map((r,i)=>`<span class="tag">${esc(r)} <button class="row-action" data-delete="room" data-id="${i}">×</button></span>`).join('')}
function renderLessons(filter=''){const q=filter.toLowerCase(),ls=state.lessons.filter(l=>[l.subject,className(l.classId),teacherName(l.teacherId)].some(x=>x.toLowerCase().includes(q)));$('#lesson-summary').textContent=`${ls.length} requirements · ${ls.reduce((n,l)=>n+Number(l.count),0)} weekly periods`;$('#lessons-body').innerHTML=ls.map(l=>`<tr><td><strong>${className(l.classId)}</strong></td><td>${esc(l.subject)}</td><td>${esc(teacherName(l.teacherId))}</td><td>${l.count}</td><td class="muted">${esc(l.room||'Home room')}</td><td><button class="row-action" data-delete="lesson" data-id="${l.id}">×</button></td></tr>`).join('')}
function generate(){const issues=validate(false);if(issues.length){toast(issues[0]);showView('setup');return}schedule=[];unplaced=[];const days=dayNames(),periods=+state.settings.periods,instances=[];state.lessons.forEach(l=>{for(let i=0;i<+l.count;i++)instances.push({...l,instance:i})});instances.sort((a,b)=>constraintScore(b)-constraintScore(a));const occupied={};for(const item of instances){const slots=[];for(let d=0;d<days.length;d++)for(let p=1;p<=periods;p++){const score=slotScore(item,d,p,occupied,days);if(score!==null)slots.push({d,p,score:score+Math.random()*.15})}slots.sort((a,b)=>a.score-b.score);if(!slots.length){unplaced.push(item);continue}const s=slots[0],entry={...item,day:s.d,period:s.p};schedule.push(entry);mark(occupied,entry)}renderScheduleControls();showView('timetable');$('#generation-note').textContent=`Generated just now · ${schedule.length} of ${instances.length} lessons placed`;$('#schedule-alert').innerHTML=unplaced.length?`<div class="alert">${unplaced.length} lesson${unplaced.length>1?'s':''} could not be placed. Reduce loads, add periods, or loosen teacher availability.</div>`:`<div class="alert success">All ${schedule.length} lessons placed with no teacher, class or room clashes.</div>`;renderSchedule();toast(unplaced.length?'Timetable generated with warnings':'Conflict-free timetable generated')}
function constraintScore(l){const t=state.teachers.find(x=>x.id===l.teacherId);return (l.room?5:0)+(t?.unavailable?3:0)+Number(l.count)}
function slotScore(item,d,p,o,days){const day=days[d].slice(0,3),key=`${d}-${p}`,t=state.teachers.find(x=>x.id===item.teacherId),c=state.classes.find(x=>x.id===item.classId),room=item.room||c.room;if(t.unavailable.split(',').map(x=>x.trim()).includes(`${day}-${p}`))return null;if(o[`t:${item.teacherId}:${key}`]||o[`c:${item.classId}:${key}`]||o[`r:${room}:${key}`])return null;const daily=schedule.filter(x=>x.teacherId===item.teacherId&&x.day===d).length;if(daily>=+t.max)return null;const subjectToday=schedule.filter(x=>x.classId===item.classId&&x.subject===item.subject&&x.day===d).length;const classDaily=schedule.filter(x=>x.classId===item.classId&&x.day===d).length;return subjectToday*12+classDaily*1.3+daily*.8+(p===1||p===+state.settings.periods?1:0)}
function mark(o,e){const k=`${e.day}-${e.period}`,c=state.classes.find(x=>x.id===e.classId),r=e.room||c.room;o[`t:${e.teacherId}:${k}`]=o[`c:${e.classId}:${k}`]=o[`r:${r}:${k}`]=true}
function renderScheduleControls(){const mode=$('#schedule-mode').value||'class',items=mode==='class'?state.classes:state.teachers,old=$('#schedule-entity').value;$('#schedule-entity').innerHTML=items.map(x=>`<option value="${x.id}">${mode==='class'?className(x.id):esc(x.name)}</option>`).join('');if(items.some(x=>x.id===old))$('#schedule-entity').value=old;renderSchedule()}
function renderSchedule(){const mode=$('#schedule-mode').value,entity=$('#schedule-entity').value,days=dayNames(),periods=+state.settings.periods;if(!schedule.length){$('#schedule-table').innerHTML=`<tbody><tr><td class="muted" style="padding:70px">No timetable generated yet.</td></tr></tbody>`;return}let html='<thead><tr><th>Period</th>'+days.map(d=>`<th>${d}</th>`).join('')+'</tr></thead><tbody>';for(let p=1;p<=periods;p++){html+=`<tr><th>Period ${p}</th>`;for(let d=0;d<days.length;d++){const s=schedule.find(x=>x.day===d&&x.period===p&&(mode==='class'?x.classId===entity:x.teacherId===entity));html+=`<td>${s?slotHtml(s,mode):'<div class="slot empty">—</div>'}</td>`}html+='</tr>'}$('#schedule-table').innerHTML=html+'</tbody>'}
function slotHtml(s,mode){const practical=/science|computer|art|physical/i.test(s.subject),language=/english|hindi|language/i.test(s.subject),type=practical?'practical':language?'language':'core';return `<div class="slot ${type}"><strong>${esc(s.subject)}</strong><small>${mode==='class'?esc(teacherName(s.teacherId)):className(s.classId)} · ${esc(s.room||state.classes.find(c=>c.id===s.classId)?.room||'')}</small></div>`}
function validate(notify=true){const issues=[];if(!state.teachers.length)issues.push('Add at least one teacher.');if(!state.classes.length)issues.push('Add at least one class.');if(!state.lessons.length)issues.push('Add at least one lesson requirement.');state.lessons.forEach(l=>{if(!state.teachers.some(t=>t.id===l.teacherId)||!state.classes.some(c=>c.id===l.classId))issues.push(`Fix the assignment for ${l.subject}.`)});if(notify)toast(issues.length?issues[0]:'Your setup is complete and consistent');return issues}
function openEditor(type){const fields=$('#dialog-fields'),titles={teacher:'Add teacher',class:'Add class',room:'Add room',lesson:'Add lesson requirement'};$('#dialog-title').textContent=titles[type];$('#editor-form').dataset.type=type;if(type==='teacher')fields.innerHTML=field('name','Full name')+field('code','Short code')+field('max','Max periods / day','number','5')+field('unavailable','Unavailable slots','text','','e.g. Mon-1,Wed-4','full');if(type==='class')fields.innerHTML=field('grade','Grade')+field('section','Section')+selectField('room','Home room',state.rooms);if(type==='room')fields.innerHTML=field('name','Room name','text','','e.g. Science Lab','full');if(type==='lesson')fields.innerHTML=selectField('classId','Class',state.classes.map(c=>({value:c.id,label:className(c.id)})))+field('subject','Subject')+selectField('teacherId','Teacher',state.teachers.map(t=>({value:t.id,label:t.name})))+field('count','Lessons per week','number','4')+selectField('room','Special room (optional)',['',...state.rooms]);$('#editor-dialog').showModal()}
function field(name,label,type='text',value='',placeholder='',cls=''){return `<label class="${cls}">${label}<input name="${name}" type="${type}" value="${value}" placeholder="${placeholder}" ${type==='number'?'min="1" max="10"':''} required></label>`}
function selectField(name,label,items){return `<label>${label}<select name="${name}">${items.map(x=>{const v=typeof x==='string'?x:x.value,l=typeof x==='string'?(x||'Home room'):x.label;return `<option value="${esc(v)}">${esc(l)}</option>`}).join('')}</select></label>`}
function submitEditor(e){e.preventDefault();const type=e.currentTarget.dataset.type,d=Object.fromEntries(new FormData(e.currentTarget));if(type==='teacher')state.teachers.push({id:uid(),name:d.name,code:d.code.toUpperCase(),max:+d.max,unavailable:d.unavailable});if(type==='class')state.classes.push({id:uid(),grade:d.grade,section:d.section.toUpperCase(),room:d.room});if(type==='room')state.rooms.push(d.name);if(type==='lesson')state.lessons.push({id:uid(),classId:d.classId,subject:d.subject,teacherId:d.teacherId,count:+d.count,room:d.room});save();render();$('#editor-dialog').close()}
function remove(type,id){if(type==='teacher'){state.teachers=state.teachers.filter(x=>x.id!==id);state.lessons=state.lessons.filter(x=>x.teacherId!==id)}if(type==='class'){state.classes=state.classes.filter(x=>x.id!==id);state.lessons=state.lessons.filter(x=>x.classId!==id)}if(type==='lesson')state.lessons=state.lessons.filter(x=>x.id!==id);if(type==='room')state.rooms.splice(+id,1);schedule=[];save();render()}
function dayNames(){return ['Monday','Tuesday','Wednesday','Thursday','Friday','Saturday'].slice(0,+state.settings.days)}function uid(){return Date.now().toString(36)+Math.random().toString(36).slice(2,6)}function esc(v=''){return String(v).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}function toast(msg){const el=$('#toast');el.textContent=msg;el.classList.add('show');clearTimeout(toast.t);toast.t=setTimeout(()=>el.classList.remove('show'),2200)}
document.addEventListener('click',e=>{const v=e.target.closest('[data-view]'),a=e.target.closest('[data-action]'),add=e.target.closest('[data-add]'),del=e.target.closest('[data-delete]');if(v)showView(v.dataset.view);if(add)openEditor(add.dataset.add);if(del)remove(del.dataset.delete,del.dataset.id);if(a){if(a.dataset.action==='generate')generate();if(a.dataset.action==='validate')validate();if(a.dataset.action==='print'){showView('timetable');setTimeout(print,100)}if(a.dataset.action==='reset-demo'){state=structuredClone(DEMO);schedule=[];save();render()}}});
$('#editor-form').addEventListener('submit',submitEditor);$('#lesson-search').addEventListener('input',e=>renderLessons(e.target.value));$('#working-days').addEventListener('change',e=>{state.settings.days=+e.target.value;schedule=[];save()});$('#periods-day').addEventListener('change',e=>{state.settings.periods=+e.target.value;schedule=[];save()});$('#schedule-mode').addEventListener('change',renderScheduleControls);$('#schedule-entity').addEventListener('change',renderSchedule);$('.mobile-menu').addEventListener('click',()=>$('.sidebar').classList.toggle('open'));render();
